### ISSUE TITLE
https://cdglabs.org/prolog broken

### ISSUE THREAD

**Issue by ToonTalk** [cdglabs/prolog#2]
But http://cdglabs.github.io/prolog works.

Nice visualizer!

Also you may find this interesting which animated a backtracking tree when using definite clause grammar in Prolog:
 Ken Kahn. A grammar kit in Prolog. In M. Yazdani, editor, New Horizons in Educational Computing. Ellis Horwood Ltd., 1984. Also In Instructional Science and Proceedings of the AISB Easter Conference on AI and Education, Exeter, England, April 1983.

**Comment by l00mi** [comment]
Currently https://cdglabs.github.io/prolog-viz/ works.

**Comment by ToonTalk** [comment]
Nice!

**Comment by alexwarth** [comment]
See #3.
