### ISSUE TITLE
Website broken/down?

### ISSUE THREAD

**Issue by iloos** [cdglabs/prolog#3]
Hey, I was wondering if the prolog visualizer was still avaliable? The website is down and I cannot find an alternative link, or a way to open the program locally. Thanks

**Comment by l00mi** [comment]
Try https://cdglabs.github.io/prolog-viz/, cheers.

**Comment by l00mi** [comment]
If anyone @pdubroy @tonyg @mpnagle is still is around. Simply changing the website link on the [repo front page](https://github.com/cdglabs/prolog-viz) would make generate some more 😃 .

**Comment by alexwarth** [comment]
>
> If anyone @pdubroy <https://github.com/pdubroy> @tonyg
> <https://github.com/tonyg> @mpnagle <https://github.com/mpnagle> is still
> is around. Simply changing the website link on the repo front page
> <https://github.com/cdglabs/prolog-viz> would make generate some more 😃 .
>

Thanks for the heads up, guys. I just updated the page with the updated
link.

Best,
Alex
